# Generated by Django 3.2.6 on 2021-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapBS4', '0003_worddictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddictionary',
            name='meaning',
            field=models.CharField(default='', max_length=500),
        ),
    ]
