# Generated by Django 3.2.6 on 2021-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapBS4', '0004_worddictionary_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddictionary',
            name='search',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='worddictionary',
            name='meaning',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
