# Generated by Django 3.2.6 on 2021-08-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapBS4', '0005_auto_20210812_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=160)),
                ('keywords', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timeStamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='worddictionary',
            options={'ordering': ('-timeStamp',)},
        ),
    ]
